export type BibleBook = {
  n: number;
  nome: string;
  slug: string;
  caps: number;
  nt?: boolean;
};

export const bibleBooks: BibleBook[] = [
  { n: 1, nome: "Gênesis", slug: "genesis", caps: 50 },
  { n: 2, nome: "Êxodo", slug: "exodus", caps: 40 },
  { n: 3, nome: "Levítico", slug: "leviticus", caps: 27 },
  { n: 4, nome: "Números", slug: "numbers", caps: 36 },
  { n: 5, nome: "Deuteronômio", slug: "deuteronomy", caps: 34 },
  { n: 6, nome: "Josué", slug: "joshua", caps: 24 },
  { n: 7, nome: "Juízes", slug: "judges", caps: 21 },
  { n: 8, nome: "Rute", slug: "ruth", caps: 4 },
  { n: 9, nome: "1 Samuel", slug: "1%20samuel", caps: 31 },
  { n: 10, nome: "2 Samuel", slug: "2%20samuel", caps: 24 },
  { n: 11, nome: "1 Reis", slug: "1%20kings", caps: 22 },
  { n: 12, nome: "2 Reis", slug: "2%20kings", caps: 25 },
  { n: 13, nome: "1 Crônicas", slug: "1%20chronicles", caps: 29 },
  { n: 14, nome: "2 Crônicas", slug: "2%20chronicles", caps: 36 },
  { n: 15, nome: "Esdras", slug: "ezra", caps: 10 },
  { n: 16, nome: "Neemias", slug: "nehemiah", caps: 13 },
  { n: 17, nome: "Ester", slug: "esther", caps: 10 },
  { n: 18, nome: "Jó", slug: "job", caps: 42 },
  { n: 19, nome: "Salmos", slug: "psalms", caps: 150 },
  { n: 20, nome: "Provérbios", slug: "proverbs", caps: 31 },
  { n: 21, nome: "Eclesiastes", slug: "ecclesiastes", caps: 12 },
  { n: 22, nome: "Cantares", slug: "song%20of%20solomon", caps: 8 },
  { n: 23, nome: "Isaías", slug: "isaiah", caps: 66 },
  { n: 24, nome: "Jeremias", slug: "jeremiah", caps: 52 },
  { n: 25, nome: "Lamentações", slug: "lamentations", caps: 5 },
  { n: 26, nome: "Ezequiel", slug: "ezekiel", caps: 48 },
  { n: 27, nome: "Daniel", slug: "daniel", caps: 12 },
  { n: 28, nome: "Oséias", slug: "hosea", caps: 14 },
  { n: 29, nome: "Joel", slug: "joel", caps: 3 },
  { n: 30, nome: "Amós", slug: "amos", caps: 9 },
  { n: 31, nome: "Obadias", slug: "obadiah", caps: 1 },
  { n: 32, nome: "Jonas", slug: "jonah", caps: 4 },
  { n: 33, nome: "Miqueias", slug: "micah", caps: 7 },
  { n: 34, nome: "Naum", slug: "nahum", caps: 3 },
  { n: 35, nome: "Habacuque", slug: "habakkuk", caps: 3 },
  { n: 36, nome: "Sofonias", slug: "zephaniah", caps: 3 },
  { n: 37, nome: "Ageu", slug: "haggai", caps: 2 },
  { n: 38, nome: "Zacarias", slug: "zechariah", caps: 14 },
  { n: 39, nome: "Malaquias", slug: "malachi", caps: 4 },
  { n: 40, nome: "Mateus", slug: "matthew", caps: 28, nt: true },
  { n: 41, nome: "Marcos", slug: "mark", caps: 16, nt: true },
  { n: 42, nome: "Lucas", slug: "luke", caps: 24, nt: true },
  { n: 43, nome: "João", slug: "john", caps: 21, nt: true },
  { n: 44, nome: "Atos", slug: "acts", caps: 28, nt: true },
  { n: 45, nome: "Romanos", slug: "romans", caps: 16, nt: true },
  { n: 46, nome: "1 Coríntios", slug: "1%20corinthians", caps: 16, nt: true },
  { n: 47, nome: "2 Coríntios", slug: "2%20corinthians", caps: 13, nt: true },
  { n: 48, nome: "Gálatas", slug: "galatians", caps: 6, nt: true },
  { n: 49, nome: "Efésios", slug: "ephesians", caps: 6, nt: true },
  { n: 50, nome: "Filipenses", slug: "philippians", caps: 4, nt: true },
  { n: 51, nome: "Colossenses", slug: "colossians", caps: 4, nt: true },
  { n: 52, nome: "1 Tessalonicenses", slug: "1%20thessalonians", caps: 5, nt: true },
  { n: 53, nome: "2 Tessalonicenses", slug: "2%20thessalonians", caps: 3, nt: true },
  { n: 54, nome: "1 Timóteo", slug: "1%20timothy", caps: 6, nt: true },
  { n: 55, nome: "2 Timóteo", slug: "2%20timothy", caps: 4, nt: true },
  { n: 56, nome: "Tito", slug: "titus", caps: 3, nt: true },
  { n: 57, nome: "Filemom", slug: "philemon", caps: 1, nt: true },
  { n: 58, nome: "Hebreus", slug: "hebrews", caps: 13, nt: true },
  { n: 59, nome: "Tiago", slug: "james", caps: 5, nt: true },
  { n: 60, nome: "1 Pedro", slug: "1%20peter", caps: 5, nt: true },
  { n: 61, nome: "2 Pedro", slug: "2%20peter", caps: 3, nt: true },
  { n: 62, nome: "1 João", slug: "1%20john", caps: 5, nt: true },
  { n: 63, nome: "2 João", slug: "2%20john", caps: 1, nt: true },
  { n: 64, nome: "3 João", slug: "3%20john", caps: 1, nt: true },
  { n: 65, nome: "Judas", slug: "jude", caps: 1, nt: true },
  { n: 66, nome: "Apocalipse", slug: "revelation", caps: 22, nt: true },
];
